# GitHub release notes configuration.
# https://docs.github.com/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: Highlights
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
